import React from 'react';

const articles = {
    1: <article className="blog-tease">
            <h2>Vietnam</h2>
            <p className="date">7/5/2019</p>
            <img src="../images/vietnam.jpg" alt="..." />
            <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum quia sint delectus fugit earum, cum recusandae, esse fugiat iure eius odio sapiente accusantium dolor, eligendi dignissimos qui enim dolorem unde.</span>
            <span>Necessitatibus eos ratione nulla eius, vel repudiandae corrupti nihil? Atque rem, necessitatibus excepturi iusto maiores harum itaque, animi natus ullam voluptas laboriosam voluptatum enim laborum, ad facere quaerat porro possimus?</span>
            <span>Temporibus eaque suscipit accusamus voluptatem aperiam fugiat hic libero laboriosam voluptatum quibusdam aut culpa perspiciatis tenetur dolor dolores qui eveniet nobis ipsa quod quaerat, eum officiis impedit obcaecati. Numquam, sapiente.</span>
            <span>Id expedita tenetur autem voluptatum aperiam veniam accusamus at dolorem tempore eum est, nihil pariatur fugiat dignissimos modi, doloribus animi eveniet dolorum officia nam, ipsum dicta. Voluptatibus, in laborum harum.</span>
            <span>Mollitia neque suscipit facere omnis dolorem ratione laudantium autem inventore amet alias vero, unde soluta, velit aliquid distinctio. Voluptas, accusamus ullam iure. Et, quae repudiandae possimus voluptatibus laboriosam nam iusto?</span></p>
            <p>
            Ultrices quisque euismod mattis sapien dictumst dictumst vel quis massa interdum morbi porta? Sagittis blandit nascetur urna. Urna sit lobortis quam curae; orci fames sagittis phasellus gravida lectus mauris phasellus! Nunc non sociis curae; placerat tincidunt vehicula morbi dignissim. Aenean risus natoque tincidunt vel bibendum. Ante tortor habitant cursus semper.
            </p>
            <p>
            Curabitur euismod quis quisque dignissim. Tempus, faucibus integer suscipit. Placerat gravida litora aenean litora himenaeos dis sollicitudin consectetur fermentum morbi orci blandit. Laoreet lobortis aliquam id bibendum facilisis. Pharetra massa sapien sit enim cursus porta. Consequat erat fermentum amet. Dictumst phasellus curabitur phasellus dis facilisis duis sem potenti ac quam dictum viverra. Eleifend metus lacus faucibus proin porta sodales, ad hac porttitor sodales suspendisse. Malesuada rhoncus ridiculus sed placerat nisi vitae. Pulvinar.
            </p>
            <p>
            Varius augue turpis, fermentum cubilia. Tincidunt ad, elit mus. Placerat ultricies aptent, sagittis scelerisque parturient hendrerit felis dictum nullam. Eu lorem condimentum ullamcorper ultrices massa placerat nullam per class aliquet dapibus sodales. Ridiculus mauris, rhoncus dis neque. Consequat cras quis consectetur. Himenaeos aliquet pharetra nulla feugiat sociis ad velit porttitor.
            </p>
            <p>
            Maecenas lacinia molestie ac aptent adipiscing proin mattis pretium montes curabitur semper facilisis. Primis maecenas pretium laoreet litora. Tempor suscipit mi phasellus. Vivamus quam sagittis sociis fames vel urna. Dolor platea ornare, nascetur cras luctus iaculis cubilia augue leo pharetra nam convallis. Venenatis luctus cum tristique laoreet ullamcorper aptent primis dapibus eu nisl quis. Lacinia hendrerit fringilla quam risus augue auctor condimentum et? Tempus pretium aliquam massa mus. Etiam hac sapien semper morbi metus habitasse ligula at commodo vestibulum condimentum sed. Mattis.
            </p>
            <p>
            Aenean tellus lacus urna odio lacinia bibendum ligula, aptent tempus. Pretium cras maecenas nullam massa nunc neque pulvinar adipiscing. Nunc penatibus purus faucibus mattis consequat convallis gravida varius, penatibus quis. Magnis dis primis aliquam lorem id aliquam, sociosqu rhoncus pharetra nibh ullamcorper arcu. Lorem cum aenean integer fusce ornare posuere tortor. Parturient sollicitudin lectus vestibulum arcu, convallis metus sed convallis ridiculus magnis maecenas cras? Venenatis accumsan ultrices ante vel mollis vel diam at. Vestibulum dui nam ridiculus. Quam ornare platea pharetra mauris sapien potenti aptent parturient sapien. Fringilla interdum et faucibus senectus nunc molestie pretium consequat venenatis tempor varius ultrices. Adipiscing velit malesuada rhoncus litora dolor tincidunt sociosqu ultricies molestie ut mus. Sapien mattis dictum vestibulum conubia. Mollis nulla cum netus adipiscing, gravida dignissim nisl nulla conubia rutrum. Luctus volutpat nibh et. Netus adipiscing, risus vehicula at suspendisse. Vestibulum congue ultricies imperdiet praesent suspendisse?
            </p>
            <p>
            Nisl duis penatibus tellus varius. Luctus felis felis praesent porta sit dictumst per cursus. Dolor dolor est pellentesque venenatis potenti. Quisque vehicula parturient mus cum, magnis aliquet gravida tempor. Himenaeos lacus himenaeos sollicitudin fermentum rhoncus nec eget a lorem curabitur feugiat dolor! Ante mauris convallis tempus penatibus sit duis auctor iaculis porttitor cursus aptent. Porta phasellus maecenas adipiscing facilisi. Ridiculus parturient pulvinar suscipit rhoncus! Mattis sociosqu.
            </p>
            <p>
            Dignissim feugiat id augue. Condimentum integer, ornare etiam bibendum. Risus senectus montes rhoncus senectus sagittis nullam vehicula, magna vestibulum netus. Magna sapien aptent sed cursus senectus molestie turpis nisl. Lorem sociis tempor pharetra fames. Sociis elit interdum donec netus pellentesque sit iaculis tristique eros justo cubilia. Sollicitudin libero suspendisse vulputate. Lorem sapien dignissim sapien laoreet ipsum diam scelerisque sodales faucibus urna luctus cras. Laoreet orci accumsan suscipit amet. Augue elit at sit enim penatibus. Bibendum ullamcorper convallis pharetra dignissim habitasse torquent sodales? Cubilia tortor sociosqu rhoncus, accumsan dis ipsum quam ante tempus iaculis varius diam. Senectus vehicula semper orci porttitor dis, euismod magna rhoncus massa conubia. Ut sapien neque libero malesuada amet nec maecenas congue. Est.
            </p>
        </article>,
    2: <article className="blog-tease">
            <h2>Singapore</h2>
            <p className="date">7/1/2019</p>
            <img src="../images/singapore.jpg" alt="..." />
            <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta error laboriosam quaerat, animi, necessitatibus neque libero consectetur enim recusandae mollitia asperiores dolores odit perspiciatis facilis. Possimus rem natus maiores molestias?</span>
            <span>Voluptatibus, quia. Assumenda quisquam nulla quia iste voluptatibus quibusdam libero consequuntur minus, omnis doloremque, esse ab, veniam cumque voluptatum amet distinctio qui ipsum reprehenderit nesciunt quis aperiam id atque quas.</span>
            <span>Magni quo vel culpa magnam nostrum eos quidem soluta, nemo tempore dolor, placeat quia maiores velit atque, iure ea aut. Expedita tenetur qui amet nemo, sapiente at dicta, accusamus error!</span></p>
            <p>
            Abattoir cypher face, abbott montoya temblor of deathstroke faith? Hush luthor zatanna copperhead night lillian cluemaster jason, dick carmine firefly atomic firefly. Atom snake damian abbott grayson grey collector azrael barrow zatanna ali wayne falcone. Abdullah scarecrow sinestro nocturna scorn moth? Moth calendar atom nyssa todd, wing freeze black catwoman ra hatter poison. America deathstroke ragman night oswald lazarus. Gotham lantern raatko czonk deathstroke blue abdullah copperhead temblor atkins. Penguin cypher, katana basil fright copperhead. Society harlequin selina snake gleeson strange caird toymaker atomic cain basil grey. Freeze martha shiva blake harlequin. Cypher jester knight green todd joker! Carmine gargoyle, killer shrike harley abdullah temblor firebug gleeson clench vale. Damian, lex oracle arrow ragdoll. Temblor fright chimera quinn kobra atomic. Carmine batgirl hush outsider ghul lillian clench maxie basil grey rhino poison face. Fright ghul joker jim atkins batman justice gleeson ghul batmobile aquaman, batcave falcone?
            </p>
            <p>
            Ragdoll flash anarky ivy. Croc rumor elongated strange atomic hammer supergirl moth ragman arkham atomic solomon. Martha maroni damian grayson flash jim maxie hood quinn quinn batgirl katana boomerang. Vale lillian falcone kobra smoke joker, oracle elongated. Firefly bennett riddler harley firebug kyle aiko birds ivy czonk blink rumor. Grundy harley rose aiko jester azrael fairchild the spoiler moth creeper.
            </p>
            <p>
            Harvey batman poison sinestro phantom lazarus katana. Atom rose robin nyssa harlequin wing maxie? Kyle flash joker blue? Mad kobra league blake batman rumor. Barrow selina nyssa fairchild of zatanna bullock phantom mugsy vale. Clench maxie maroni clock crane wing bullock thomas two. Red bruce kyle calendar ra shiva copperhead spoiler grey hatter clayface harvey. Chimera faith helena cluemaster, clayface lantern cobblepot. Moth todd, kane sinestro spectre boomerang strange shrike penguin. Abbott martha prey ventriloquist nocturna. Jason harvey carmine society beetle luthor bruce. Kane drake toymaker atom thorne, mask checkmate batman mister dick. Lazarus cypher atom justice, damian selina penguin spectre hush kobra czonk. Shrike strange moth beetle knight atkins oracle shrike croc mask. Nyssa, maxie aquaman ragman thorne boomerang selina. Cain gargoyle chimera toymaker mad.
            </p>
            <p>
            Spoiler elongated, creeper hangman. Two maxie, fox nigma copperhead al al strange night. Mugsy riddler prey jim ragdoll cluemaster, atomic freeze. Oracle ventriloquist poison checkmate superman tally swamp rumor lazarus canary joker. Dent raatko red ra mugsy metallo vicki? Outsider owl mister, azrael tally batcave quinn scarecrow. Ragman metallo clock arrow. Nigma blake tumbler batgirl cypher green rose abdullah. Snake prey superman chase. Amanda jason pennyworth gleeson? Shade vale joker, young hammer cypher. Fright carmine lantern grayson penguin flash? Barrow freeze barrow alfred crane joker maxie. Bat young america collector czonk the jason. Hatter?
            </p>
            <p>
            Todd caird atomic wing wing anarky edward society maxie calendar huntress fright lynx. Clench mugsy spectre dick flash. Robin nigma joe alfred alfred nigma phantom killer collector kobra? Oracle thorne, collector birds! Alfred maxie, doom charlatan charlatan boomerang fox copperhead elongated blake. Charlatan nyssa chill todd bennett penguin checkmate batcave phantom bartok nigma. Superman caird beetle zeus crane? Boomerang alfred hammer nocturna, supergirl helena lex shiva. Hush clench checkmate blake lillian deadshot bane arrow czonk? Gearhead.
            </p>
            <p>
            Hood penguin abbott lex basil justice gleeson fright oracle rose pennyworth. Arrow master society ragman rupert oracle gotham beetle oracle hugo? Copperhead knight calendar doom batarang killer creeper batarang hatter thorne. Phantom damian atomic raatko montoya justice supergirl hangman? Barrow lynx, abbott fairchild zatanna pit. Batcave barbara penguin owl league. Gargoyle strange killer dick? Mad kobra fairchild vale thomas harley. Lucius.
            </p>
            <p>
            Ghul calendar shiva sinestro a temblor shiva. Abdullah ragdoll barrow doom outsider bullock caird! Toymaker hatter gotham raatko boomerang martha martha calendar. Atomic, barbara amanda dent. Helena atkins a, batgirl amanda spoiler. Boomerang blink of swamp snake damian scarecrow ghul flash crane fairchild. Ghul maxie thomas vale cluemaster flash. Dent kane bartok bartok drake chill? Two deathstroke ghul robin strange hugo fright. Ivy chimera crane cobblepot abbott bat lynx barrow bullock? Harvey shadow catwoman aquaman barrow dick hush poison cypher master luthor! Face zeus owl moth nocturna bane killer beetle penguin.
            </p>
        </article>,
    3: <article className="blog-tease">
            <h2>Thailand</h2>
            <p className="date">5/2/2019</p>
            <img src="../images/thailand.jpg" alt="..." />
            <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias, neque dolores quas facilis iure dolorum numquam, fugit explicabo deserunt tempore eveniet blanditiis. Numquam, et, iste magnam ex blanditiis totam eos?</span>
            <span>Molestias omnis vero porro esse, recusandae doloribus eum architecto provident animi iure asperiores dolores corporis nemo! Aspernatur dicta, quam ipsam dignissimos quaerat dolores pariatur, id sunt eos explicabo rem, assumenda.</span>
            <span>Iusto distinctio accusantium inventore nobis velit dolor ipsa magni illo porro, fugiat sequi, eaque nihil facilis magnam. Assumenda iure illum tempore commodi placeat facere, quos, distinctio recusandae error, asperiores fugiat!</span></p>
            <p>
            Skreet ff emmafrost mrhyde emmafrost maelstrom reaper wolverine. Mystique korvac loki meltdown. Madrox magik zemo rockslide flatman. Romanoff ff karnak psylocke darkstar. Leech masque invaders msmarvel blackknight magik namora blackpanther barton ultron. Blackcat bishop howard moonknight stryfe, medusa nefaria. Darkhawk madrox suestorm caliban havok elektra klaw danvers wiccan dumdum. Frankenstein araña cardiac dracula ghostrider hellcat wonderman lightspeed barton mojo. Tinkerer speedball antman toro warlock elixir, wildchild star-lord punisher faustus moltenman danvers. Mrfantastic ff avengers shang-chi snowbird.
            </p>
            <p>
            Spider-ham taskmaster ironpatriot lockheed wong. Blackheart maelstrom deathstrike nighthawk penance madrox howlett powerman excalibur prowler. Quasimodo scorpion eternals zola goliath dugan. Ka-zar nomad skaar beyonder whirlwind gorgon typhoidmary crossbones maestro runaways! Jameson, msmarvel annihilus ronan. Bug changeling sage octopus. Karma odin bucky namor xavier! Tchalla zemo redskull mephisto, dynamo deadpool korvac daken x-51 mrnegative professorx arcade. Nightmare swordsman humantorch blackheart titania dynamo. Johnnyblaze pride, hercules dagger kingcobra arcade. Microchip banner warbird archangel deathstrike parker prism giantman mrnegative shard quasar!
            </p>
            <p>
            Zodiak yellowjacket mrfantastic wolverine sunspot bug warbound dumdum bushwacker grimreaper. Banshee defenders thor psylocke electro steverogers rasputin stryfe falcon wong. Vanisher pride demogoblin tarantula, dust angela grandmaster songbird toro squirrel-girl. Lukecage proudstar mistyknight cable spot sif lilandra beast wolfsbane armadillo wilsonfisk maverick. Daken manthing sugarman daken urich marrow firelord lockjaw xorn? Kronos jeangrey xorn toad fisk prism pryde quasimodo enchantress firebrand prism. Fantomex callisto romanoff titania arachne kitty dumdum blastaar maelstrom. Lizard emmafrost mistyknight lilandra sprite shocker ares scarletspider howard madthinker atlas angela. Batroc vision deathstrike mrnegative doom sif medusa dynamo captainbritain mrnegative bullseye echo. Blackpanther professorx tombstone kaine harrier sif rand. Harrier conners lifeguard spider-ham banner jigsaw howard husk strange calypso morlun. Gargoyle rhino caretaker kree x-men runaways, annihilus sabretooth microchip. Snowbird thanos wendigo changeling wasp polaris electro. Mauler moonstar cardiac reaper groot deadpool kingcobra juggernaut barton doom. Chameleon shield bob tigra excalibur.
            </p>
            <p>
            Magik hellion modok mentor cyclops cannonball, sentry electro constrictor purpleman lifeguard banner. Jigsaw mimic penance, korath scourge. Scorpion manwolf leech toro quasimodo spot miek. Titania ironman xavier sentry contessa mysterio foggy star-lord! Romulus atlas rhodes hankpym x-factor quentinquire cable johnnyblaze sabretooth pepperpotts? Sunspot mayparker, sabretooth quasar greengoblin sage. Ultron drax blackwidow scorpion elixir she-hulk. Squirrel-girl colossus swordsman.
            </p>
            <p>
            Tarantula; gorgon stryfe prism. Benreilly doom foggy norrinradd hyperion agentx groot! Blastaar scarletspider batroc jarvis. Janefoster gladiator microchip professorx titania sif morbius sin maestro? Hercules blackwidow lockjaw zodiak nomad urich, jessicadrew hulkling earthquake abomination. Amora stick araña gorgon. Abomb; jimmywoo cypher bucky meltdown mockingbird. Moonstar logan zemo steverogers moonstar dracula sauron crusher! Barton romulus vulture wasp goliath x-statix gargoyle jameson dynamo wilsonfisk warpath quasar. Thing chimera unionjack, sugarman marrow? Jessicajones proudstar morph nefaria swordsman masque bushwacker. Greengoblin northstar echo sage. Angela quicksilver scrambler prowler spot whirlwind vulture phalanx shaman sage howlett zemo! Drax pryde octopus dynamo toxin doop sauron domino wolverine ironpatriot valkyrie pride lockheed. Quicksilver mongoose blink deadpool spider-man romanoff mentallo! Carnage bushwacker empath dormammu. Mauler x-statix lizard romanoff nickfury, x-factor carnage rhodes. Fisk.
            </p>
            <p>
            Hawkeye, firebird wonderman unionjack morlocks zemo manwolf scorpion moonstone kingpin felicia ricochet unus. Osborn rockslide azazel jeangrey redwing uatu maelstrom tinkerer ego wendigo maximus tombstone caretaker. Eternals nightmare excalibur zola proudstar shield earthquake shiar kronos korg mongoose jubilee? Piledriver toad, kraven humantorch. Sauron wildchild smasher destiny cable tusk gwen prism. Hydra dugan wiccan, warmachine spot romanoff rogue. Doop exodus doom flatman asgardian. Bug she-hulk maestro johnnyblaze piledriver hercules hulkling celestials wonderman mystique? Scarletspider proudstar x-factor braddock stick destiny gorillaman emmafrost, mrhyde karnak shadowcat harrier. Patriot havok mockingbird kang cypher calypso abomination chimera nighthawk jigsaw smasher. Firebird tonystark wolverine blink deathbird amora manthing defenders jackpot. Sprite ricochet cyber aurora shiar boomerang leech, ezekiel whiplash! Blackcat wolfsbane chameleon karnak zola. Shadowcat wiccan darkhawk x-force madthinker felicia ff jameson maximus, havok chamber. Nuke.
            </p>
            <p>
            Avengers mactaggert mystique kingpin caliban crossbones boomerang jubilee? Arcana abomb sabretooth jessicadrew kingpin moleman! Forge jocasta sasquatch cyber medusa. Satana mactaggert redskull scarletwitch lionheart barton ego arachne paladin snowbird firelord pandemic snowbird. Genis-vell mrfantastic punisher, karnak mysterio mystique vulture? Calypso ironman lifeguard sandman angel mystique, silversurfer blonsky inhumans. Bob caretaker stryfe stick falcon mysterio boomerang shiva gladiator proteus nightmare madrox countess. Tonystark daken gideon arachne jameson ink centurions.
            </p>
        </article>,
    4: <article className="blog-tease">
            <h2>Cambodia</h2>
            <p className="date">4/20/2019</p>
            <img src="../images/cambodia.jpg" alt="..." />
            <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Qui pariatur ex esse accusantium cum iure delectus. Tempora ullam, culpa nemo fugiat maxime blanditiis repudiandae iste aut ad. Odit, inventore autem.</span><span>Tempora eos odit laudantium ad placeat omnis ex dolorem dignissimos, quia cum blanditiis nobis autem quasi, soluta tenetur modi! Natus soluta optio cumque provident, quis dolorem eum fuga molestias tenetur!</span></p>
            <p>
            Koffing kirlia ferroseed jynx froslass ducklett skiploom blaziken! Kabuto corsola ditto chandelure paras eelektross. Shellder seadra deerling zweilous glaceon kabutops. Vullaby dwebble vibrava dratini. Pidgeotto geodude beldum wobbuffet emolga politoed. Goldeen; smeargle togetic flygon weepinbell floatzel cofagrigus tentacruel eelektrik espeon simipour charizard electabuzz. Cyndaquil lucario pidgey munna tentacool muk sealeo marowak zebstrika munna. Thundurus psyduck seismitoad darumaka mamoswine prinplup staryu. Crustle psyduck granbull linoone totodile pidove vespiquen azumarill slugma. Metapod cranidos ninetales electrode wobbuffet genesect. Phione staravia duskull sudowoodo genesect zigzagoon wobbuffet dunsparce probopass.
            </p>
            <p>
            Krookodile latios pupitar ferroseed chandelure swadloon, hippowdon lotad. Bronzong mamoswine hippowdon snorlax blissey uxie onix golurk sealeo honchkrow landorus vaporeon illumise. Electrike tangrowth hydreigon dwebble vileplume koffing. Cryogonal eevee sharpedo shellos latios venonat anorith moltres exploud tyrogue mewtwo nidoking mantine. Petilil dewgong barboach joltik. Tepig wooper swadloon mantine wailmer torchic sandshrew volcarona. Durant, carracosta jigglypuff blitzle deoxys vanillish lopunny cryogonal.
            </p>
            <p>
            Lileep rufflet, sneasel ninjask buneary kricketune cofagrigus flareon solosis. Wingull liepard mantine mewtwo paras. Crustle cherrim drilbur porygon; venomoth jumpluff cubchoo mothim shuckle shedinja palkia. Misdreavus lillipup elekid tranquill krabby kyogre. Herdier primeape ariados chimecho zoroark? Delibird purugly muk turtwig xatu; vanillite deerling budew mareep tangela. Whiscash lucario, gurdurr froslass armaldo palkia jumpluff ekans mienshao? Unfezant, swoobat rhyhorn persian smeargle aipom venonat hippowdon solrock? Klang flareon surskit, ralts poliwag phione venonat exeggutor camerupt crawdaunt. Durant seismitoad nidoking?
            </p>
            <p>
            Magcargo, golem shinx tepig weezing drapion? Archen staraptor armaldo toxicroak wailord munna ariados dustox nuzleaf skorupi chikorita girafarig aerodactyl. Spinda corsola nidoking tauros keldeo spoink duosion buizel. Gible volcarona snivy drifloon purrloin mienfoo beheeyem drifblim. Mantine darmanitan dratini gallade shuckle bouffalant primeape regigigas, gardevoir flaaffy. Lapras vanillite sandslash roselia staravia. Arceus klink beedrill slowbro nidoking masquerain dodrio tranquill herdier silcoon. Munchlax deino duosion venusaur dugtrio silcoon musharna spiritomb spheal? Spiritomb golduck electrode sudowoodo. Manaphy shuppet bidoof budew slugma audino mudkip breloom mantyke and snubbull audino! Tyrogue snorlax lapras landorus. Kadabra archeops shieldon scyther darumaka abomasnow, foongus machoke? Nuzleaf weedle grotle lugia magcargo starmie pichu buizel vigoroth sceptile skarmory dugtrio magneton. Gliscor wartortle crobat chinchou chimecho blaziken togekiss mantine, shaymin slakoth slowbro taillow feebas. Zigzagoon simisage terrakion murkrow, groudon groudon escavalier gyarados bronzong cubchoo machop wartortle. Stunky slowpoke patrat bagon hypno cresselia pansear.
            </p>
            <p>
            Anorith blissey wobbuffet drapion zweilous swoobat roselia weepinbell! Bidoof sawsbuck muk octillery delibird wurmple. Dugtrio farfetch gothorita vanillish hoothoot pupitar cleffa rhyperior. Druddigon pansage leafeon grimer slakoth, forretress tentacruel palpitoad? Solrock litwick mareep haxorus cubone. Grotle, sewaddle druddigon venipede pansear beedrill furret mesprit walrein. Deino, scraggy deino yanma skitty. Pikachu riolu starly solrock gallade lumineon duskull ledyba spearow monferno! Durant swampert beartic metang staryu pansage shuckle skorupi murkrow.
            </p>
            <p>
            Burmy; smeargle pikachu dratini terrakion carnivine clamperl keldeo. Flygon druddigon meganium chimecho, druddigon shinx kecleon arbok feebas. Glameow emolga bidoof deerling. Taillow herdier bronzor druddigon poliwhirl grovyle uxie of. Klang smoochum; braviary gastrodon golbat shroomish electrike sigilyph purugly raichu simipour jirachi charizard. Linoone staraptor slakoth treecko togepi armaldo gliscor servine slowking. Swellow corsola darkrai empoleon miltank snivy sharpedo unfezant snivy nuzleaf. Delcatty houndour bonsly vullaby, houndour sharpedo octillery. Cherrim swablu a cubchoo terrakion beedrill electabuzz dewott gligar misdreavus dewgong. Victini staryu numel sharpedo finneon conkeldurr kricketune gurdurr hitmonlee bouffalant huntail terrakion. Wailord tyrogue shelmet torkoal togepi. Bellsprout walrein mesprit ferroseed bisharp sneasel hoppip mawile aggron musharna eelektross swinub lombre. Tyrogue archeops magnemite weezing gigalith. Miltank volcarona emolga pinsir taillow kabuto medicham graveler entei magmar. Shiftry onix, dusknoir murkrow whiscash! Sceptile krabby swadloon quilava bellossom herdier excadrill camerupt volcarona, goldeen cresselia totodile? Pidgey sewaddle deino whirlipede. Beautifly frillish.
            </p>
            <p>
            Dustox pignite pawniard drifblim mienfoo drilbur gothita reshiram drilbur duosion mew combusken electivire? Kangaskhan uxie mantine landorus kirlia sunkern totodile pichu caterpie. Spiritomb poliwrath groudon cascoon, finneon gastrodon finneon hitmontop porygon darumaka cubone horsea pidgey. Forretress snivy alakazam natu armaldo kadabra samurott. Moltres zigzagoon, rampardos blitzle metagross ponyta espeon. Lotad tangela buneary gloom shinx bastiodon excadrill beedrill farfetch. Blissey golbat ralts mightyena cyndaquil mantine shinx stoutland magmar noctowl heatmor. Rhydon swampert jirachi.
            </p>
        </article>
}

export default articles;